<?
// 
// Header.
namespace 
	 	Cheope_ns\fw;
header("Content-type:text/xml");

// Require onces.
require_once("root.def.php");
require_once(FRAMEWORK_PATH . "Cheope_ns_ajaxOps.class.php");
require_once(FRAMEWORK_PATH . "Cheope_ns_ajax_handler.class.php");

// Defines.
define('AJAX_OP_CONTAINER_1',"ajaxOpContainer1");
define('AJAX_HANDLER_1',"ajaxHandler1");

// Generates instances.
// SEZIONE Generate instances.
// Generates instances.
$ajaxOpJavascriptInjection=new AjaxOpJavascriptInjection();
$ajaxOpLocalization=new AjaxOpLocalization();
$ajaxOpTestDir=new AjaxOpTestDir();
$ajaxOpGetScrollData=new AjaxOpGetScrollData();
$ajaxOpGetSheetData=new AjaxOpGetSheetData();
$ajaxOpGetFile=new AjaxOpGetFile();
$ajaxOpOp1=new AjaxOpOp1();
$ajaxOpOp2=new AjaxOpOp2();
$ajaxOpOp3=new AjaxOpOp3();
$ajaxOpOp4=new AjaxOpOp4();
$ajaxOpOp5=new AjaxOpOp5();
$ajaxOpOp6=new AjaxOpOp6();
$ajaxOpOp7=new AjaxOpOp7();
$ajaxOpSendFile=new AjaxOpSendFile();
$ajaxOpGetDbObjsDefProps=new AjaxOpGetDbObjsDefProps();
$ajaxOpSetDbObjsDefProps=new AjaxOpSetDbObjsDefProps();
$ajaxOpGetAllFieldsDefProps=new AjaxOpGetAllFieldsDefProps();
$ajaxOpUnblockApp=new AjaxOpUnblockApp();
$ajaxOpSetFieldsDefFieldsProps=new AjaxOpSetFieldsDefFieldsProps();
$ajaxOpSetFieldsDefAllFieldsProps=new AjaxOpSetFieldsDefAllFieldsProps();
$ajaxOpSetFieldsDefCandKeyFieldsProps=new AjaxOpSetFieldsDefCandKeyFieldsProps();
$ajaxOpSetFieldsDefExtKeyFieldsProps=new AjaxOpSetFieldsDefExtKeyFieldsProps();
$ajaxOpSet1NRelationsDefinitionProps=new AjaxOpSet1NRelationsDefinitionProps();
$ajaxOpGet1NRelations=new AjaxOpGet1NRelations();
$ajaxOpGetMNRelations=new AjaxOpGetMNRelations();
$ajaxOpSetMNRelationsDefinitionProps=new AjaxOpSetMNRelationsDefinitionProps();
$ajaxOpCreateDbStruct=new AjaxOpCreateDbStruct();
$ajaxOpPostSendInterfaceData=new AjaxOpPostSendInterfaceData();
$ajaxOpDeleteFile=new AjaxOpDeleteFile();
$ajaxOpCreateFile=new AjaxOpCreateFile();
$ajaxOpRenameFile=new AjaxOpRenameFile();
$ajaxOpCreatePage=new AjaxOpCreatePage();
$ajaxOpGetQuery=new AjaxOpGetQuery();
$ajaxOpSetQuery=new AjaxOpSetQuery();
$ajaxOpSetAllQueries=new AjaxOpSetAllQueries();
$ajaxOpCreateQueriesStruct=new AjaxOpCreateQueriesStruct();
$ajaxOpDumpAjaxOpsConstsFile=new AjaxOpDumpAjaxOpsConstsFile();
$ajaxOpAddAjaxOpsFromPhpArray=new AjaxOpAddAjaxOpsFromPhpArray();
$ajaxOpGetParents=new AjaxOpGetParents();
$ajaxOpCheckIfIs1NRelationFather=new AjaxOpCheckIfIs1NRelationFather();
$ajaxOpCheckIfIs1NRelationFatherOf=new AjaxOpCheckIfIs1NRelationFatherOf();
$ajaxOpCheckIfIs1NRelation=new AjaxOpCheckIfIs1NRelation();
$ajaxOpCheckIfExistMNRelationLinkTable=new AjaxOpCheckIfExistMNRelationLinkTable();
$ajaxOpGetFieldsDefProps=new AjaxOpGetFieldsDefProps();
$ajaxOpGetCandKeyFieldsProps=new AjaxOpGetCandKeyFieldsProps();
$ajaxOpGetExtKeyFieldsProps=new AjaxOpGetExtKeyFieldsProps();
$ajaxOpGetPkKeyField=new AjaxOpGetPkKeyField();
$ajaxOpSetPk=new AjaxOpSetPk();
$ajaxOpCheckIfIsSuitablePkKey=new AjaxOpCheckIfIsSuitablePkKey();
$ajaxOpCheckIfIsSuitableField=new AjaxOpCheckIfIsSuitableField();
$ajaxOpSetFieldsDef=new AjaxOpSetFieldsDef();
$ajaxOpSetFieldsConstsDef=new AjaxOpSetFieldsConstsDef();
$ajaxOpSetFieldsDefWithoutExtKeys=new AjaxOpSetFieldsDefWithoutExtKeys();
$ajaxOpSqlServerImport=new AjaxOpSqlServerImport();
$ajaxOpTestConnection=new AjaxOpTestConnection();
$ajaxOpViewAllFieldsOp1=new AjaxOpViewAllFieldsOp1();
$ajaxOpViewAllFieldsOp2=new AjaxOpViewAllFieldsOp2();
$ajaxOpSqlServerCreateTable=new AjaxOpSqlServerCreateTable();
$ajaxOpCheckIfKeyCollides=new AjaxOpCheckIfKeyCollides();
$ajaxOpViewAllTablesOp1=new AjaxOpViewAllTablesOp1();
$ajaxOpViewAllTablesOp2=new AjaxOpViewAllTablesOp2();
$ajaxOpViewAllRelationsOp1=new AjaxOpViewAllRelationsOp1();
$ajaxOpViewAllRelationsOp2=new AjaxOpViewAllRelationsOp2();
$ajaxOpRenameAllItems=new AjaxOpRenameAllItems();
$ajaxOpCheckIfKeyCollidesWithSonsKeys=new AjaxOpCheckIfKeyCollidesWithSonsKeys();
$ajaxOpCheckIfIsDataSourceQuery=new AjaxOpCheckIfIsDataSourceQuery();
$ajaxOpViewAllQueriesOp1=new AjaxOpViewAllQueriesOp1();
$ajaxOpViewAllQueriesOp2=new AjaxOpViewAllQueriesOp2();
$ajaxOpSetSessionActiveApp=new AjaxOpSetSessionActiveApp();
$ajaxOpExportQueryToCsv=new AjaxOpExportQueryToCsv();
$ajaxOpGetDbOpPars=new AjaxOpGetDbOpPars();
$ajaxOpGetConnection=new AjaxOpGetConnection();
$ajaxOpSetConnection=new AjaxOpSetConnection();
$ajaxOpCreateConnectionsStruct=new AjaxOpCreateConnectionsStruct();
$ajaxOpViewAllConnectionsOp2=new AjaxOpViewAllConnectionsOp2();
$ajaxOpCopyConnectionToDbPars=new AjaxOpCopyConnectionToDbPars();
$ajaxOpViewAllAliasesOp1=new AjaxOpViewAllAliasesOp1();
$ajaxOpViewAllAliasesOp2=new AjaxOpViewAllAliasesOp2();
$ajaxOpSetAllAliases=new AjaxOpSetAllAliases();
$ajaxOpCheckIfAliasExists=new AjaxOpCheckIfAliasExists();
$ajaxOpCheckIfTableExists=new AjaxOpCheckIfTableExists();
$ajaxOpViewTablesAndQueriesOp1=new AjaxOpViewTablesAndQueriesOp1();
$ajaxOpViewTablesAndQueriesOp2=new AjaxOpViewTablesAndQueriesOp2();
$ajaxOpViewTablesAndQueriesOp3=new AjaxOpViewTablesAndQueriesOp3();
$ajaxOpGetNodeType=new AjaxOpGetNodeType();
$ajaxOpSetAllTablesAndQueriesBinds=new AjaxOpSetAllTablesAndQueriesBinds();
$ajaxOpCreateDbBinds=new AjaxOpCreateDbBinds();
$ajaxOpUpdateBinds=new AjaxOpUpdateBinds();
$ajaxOpGetTableFromAlias=new AjaxOpGetTableFromAlias();
$ajaxOpGetLayouts=new AjaxOpGetLayouts();
$ajaxOpLayoutsOp1=new AjaxOpLayoutsOp1();
$ajaxOpLayoutsOp2=new AjaxOpLayoutsOp2();
$ajaxOpSaveLayout=new AjaxOpSaveLayout();
$ajaxOpCreateLayoutPreview=new AjaxOpCreateLayoutPreview();
$ajaxOpGetLayout=new AjaxOpGetLayout();
$ajaxOpCreatePreview=new AjaxOpCreatePreview();
$ajaxOpManageOp1=new AjaxOpManageOp1();
$ajaxOpManageOp2=new AjaxOpManageOp2();
$ajaxOpGetNamedInterfacesContainer=new AjaxOpGetNamedInterfacesContainer();
$ajaxOpGetAllTableFields=new AjaxOpGetAllTableFields();
$ajaxOpGetAllAliasFields=new AjaxOpGetAllAliasFields();
$ajaxOpGetAllQueryFields=new AjaxOpGetAllQueryFields();
$ajaxOpGetAllModuleFields=new AjaxOpGetAllModuleFields();
$ajaxOpGetAllBindFields=new AjaxOpGetAllBindFields();
$ajaxOpManageFieldsOp2=new AjaxOpManageFieldsOp2();
$ajaxOpManageFieldsOp1=new AjaxOpManageFieldsOp1();
$ajaxOpGetAllInterfacesOfPage=new AjaxOpGetAllInterfacesOfPage();
$ajaxOpFilterParentsInterfacesFiles=new AjaxOpFilterParentsInterfacesFiles();
$ajaxOpGetInterfaceIds=new AjaxOpGetInterfaceIds();
$ajaxOpExport=new AjaxOpExport();
$ajaxOpGetSingleMenus=new AjaxOpGetSingleMenus();
$ajaxOpGetMultiMenus=new AjaxOpGetMultiMenus();
$ajaxOpViewSingleMenuFieldsOp1=new AjaxOpViewSingleMenuFieldsOp1();
$ajaxOpViewSingleMenuFieldsOp2=new AjaxOpViewSingleMenuFieldsOp2();
$ajaxOpSetSingleMenu=new AjaxOpSetSingleMenu();
$ajaxOpViewMultiMenuFieldsOp1=new AjaxOpViewMultiMenuFieldsOp1();
$ajaxOpViewMultiMenuFieldsOp2=new AjaxOpViewMultiMenuFieldsOp2();
$ajaxOpSetMultiMenu=new AjaxOpSetMultiMenu();
$ajaxOpGetFreeInterfaceCanonicalName=new AjaxOpGetFreeInterfaceCanonicalName();
$ajaxOpViewBindsOp1=new AjaxOpViewBindsOp1();
$ajaxOpViewBindsOp2=new AjaxOpViewBindsOp2();
$ajaxOpViewBindsOp3=new AjaxOpViewBindsOp3();
$ajaxOpViewBindsOp4=new AjaxOpViewBindsOp4();
$ajaxOpSetAllBinds=new AjaxOpSetAllBinds();
$ajaxOpRenameAliasName=new AjaxOpRenameAliasName();
$ajaxOpGetBindNodeName=new AjaxOpGetBindNodeName();
$ajaxOpGetBindNodeType=new AjaxOpGetBindNodeType();
$ajaxOpCheckIfNodeIsUsed=new AjaxOpCheckIfNodeIsUsed();
$ajaxOpCheckIfConnectionIsUsed=new AjaxOpCheckIfConnectionIsUsed();
$ajaxOpViewBoundInterfacesOp2=new AjaxOpViewBoundInterfacesOp2();
$ajaxOpViewBoundInterfacesOp3=new AjaxOpViewBoundInterfacesOp3();
$ajaxOpSetAllBoundInterfaces=new AjaxOpSetAllBoundInterfaces();
$ajaxOpCatalogOp2=new AjaxOpCatalogOp2();
$ajaxOpCatalogOp3=new AjaxOpCatalogOp3();
$ajaxOpCatalogOp4=new AjaxOpCatalogOp4();
$ajaxOpSetAllCatalogInterfaces=new AjaxOpSetAllCatalogInterfaces();
$ajaxOpGetInterfaceItemsNum=new AjaxOpGetInterfaceItemsNum();
$ajaxOpIsInterfaceBusy=new AjaxOpIsInterfaceBusy();
$ajaxOpExportChanges=new AjaxOpExportChanges();
$ajaxOpScanForItem=new AjaxOpScanForItem();
$ajaxOpManageAjaxOp1=new AjaxOpManageAjaxOp1();
$ajaxOpManageAjaxOp2=new AjaxOpManageAjaxOp2();
$ajaxOpSetAllAjaxOps=new AjaxOpSetAllAjaxOps();
$ajaxOpManageAjaxClassesOp1=new AjaxOpManageAjaxClassesOp1();
$ajaxOpManageAjaxClassesOp2=new AjaxOpManageAjaxClassesOp2();
$ajaxOpSetAllAjaxOpsClasses=new AjaxOpSetAllAjaxOpsClasses();
$ajaxOpGenerateAjaxOpsConfigurationFiles=new AjaxOpGenerateAjaxOpsConfigurationFiles();
$ajaxOpGenerateAjaxOpsClassesFiles=new AjaxOpGenerateAjaxOpsClassesFiles();
$ajaxOpPagesInterfacesExportChanges=new AjaxOpPagesInterfacesExportChanges();
$ajaxOpViewFormsSectionGridOp1=new AjaxOpViewFormsSectionGridOp1();
$ajaxOpSaveFormSection=new AjaxOpSaveFormSection();
$ajaxOpGetFormSections=new AjaxOpGetFormSections();
$ajaxOpViewPdfTemplateGridOp1=new AjaxOpViewPdfTemplateGridOp1();
$ajaxOpSavePdfTemplate=new AjaxOpSavePdfTemplate();
$ajaxOpGetPdfTemplates=new AjaxOpGetPdfTemplates();
$ajaxOpGetObjTypeByShortName=new AjaxOpGetObjTypeByShortName();
$ajaxOpGetFpdfIntProps=new AjaxOpGetFpdfIntProps();
$ajaxOpGetPredInterfaces=new AjaxOpGetPredInterfaces();
$ajaxOpInterfaceExists=new AjaxOpInterfaceExists();
$ajaxOpCreatePdf=new AjaxOpCreatePdf();
$ajaxOpDeleteFile2=new AjaxOpDeleteFile2();
$ajaxOpGetPredInterfaces2=new AjaxOpGetPredInterfaces2();
$ajaxOpFileExists=new AjaxOpFileExists();
$ajaxOpDojoInPreview=new AjaxOpDojoInPreview();
$ajaxOpCheckIfIsInRelation=new AjaxOpCheckIfIsInRelation();
$ajaxOpDeleteRelationsDefs= new AjaxOpDeleteRelationsDefs();
$ajaxOpGetPkKeyByTableName= new AjaxOpGetPkKeyByTableName();
$ajaxOpLogEnable = new AjaxOpLogEnable();
$ajaxOpTestIntFormat = new AjaxOpTestIntFormat();
$ajaxOpFixDbXmlFiles = new AjaxOpFixDbXmlFiles();


// Adds instances to container.
$ajaxOps=new AjaxOps_container();
// SEZIONE add instances to container.
// Add instances to container.
$ajaxOps->add($ajaxOpJavascriptInjection);
$ajaxOps->add($ajaxOpLocalization);
$ajaxOps->add($ajaxOpTestDir);
$ajaxOps->add($ajaxOpGetScrollData);
$ajaxOps->add($ajaxOpGetSheetData);
$ajaxOps->add($ajaxOpGetFile);
$ajaxOps->add($ajaxOpOp1);
$ajaxOps->add($ajaxOpOp2);
$ajaxOps->add($ajaxOpOp3);
$ajaxOps->add($ajaxOpOp4);
$ajaxOps->add($ajaxOpOp5);
$ajaxOps->add($ajaxOpOp6);
$ajaxOps->add($ajaxOpOp7);
$ajaxOps->add($ajaxOpSendFile);
$ajaxOps->add($ajaxOpGetDbObjsDefProps);
$ajaxOps->add($ajaxOpSetDbObjsDefProps);
$ajaxOps->add($ajaxOpGetAllFieldsDefProps);
$ajaxOps->add($ajaxOpUnblockApp);
$ajaxOps->add($ajaxOpSetFieldsDefFieldsProps);
$ajaxOps->add($ajaxOpSetFieldsDefAllFieldsProps);
$ajaxOps->add($ajaxOpSetFieldsDefCandKeyFieldsProps);
$ajaxOps->add($ajaxOpSetFieldsDefExtKeyFieldsProps);
$ajaxOps->add($ajaxOpSet1NRelationsDefinitionProps);
$ajaxOps->add($ajaxOpGet1NRelations);
$ajaxOps->add($ajaxOpGetMNRelations);
$ajaxOps->add($ajaxOpSetMNRelationsDefinitionProps);
$ajaxOps->add($ajaxOpCreateDbStruct);
$ajaxOps->add($ajaxOpPostSendInterfaceData);
$ajaxOps->add($ajaxOpDeleteFile);
$ajaxOps->add($ajaxOpCreateFile);
$ajaxOps->add($ajaxOpRenameFile);
$ajaxOps->add($ajaxOpCreatePage);
$ajaxOps->add($ajaxOpGetQuery);
$ajaxOps->add($ajaxOpSetQuery);
$ajaxOps->add($ajaxOpSetAllQueries);
$ajaxOps->add($ajaxOpCreateQueriesStruct);
$ajaxOps->add($ajaxOpDumpAjaxOpsConstsFile);
$ajaxOps->add($ajaxOpAddAjaxOpsFromPhpArray);
$ajaxOps->add($ajaxOpGetParents);
$ajaxOps->add($ajaxOpCheckIfIs1NRelationFather);
$ajaxOps->add($ajaxOpCheckIfIs1NRelationFatherOf);
$ajaxOps->add($ajaxOpCheckIfIs1NRelation);
$ajaxOps->add($ajaxOpCheckIfExistMNRelationLinkTable);
$ajaxOps->add($ajaxOpGetFieldsDefProps);
$ajaxOps->add($ajaxOpGetCandKeyFieldsProps);
$ajaxOps->add($ajaxOpGetExtKeyFieldsProps);
$ajaxOps->add($ajaxOpGetPkKeyField);
$ajaxOps->add($ajaxOpSetPk);
$ajaxOps->add($ajaxOpCheckIfIsSuitablePkKey);
$ajaxOps->add($ajaxOpCheckIfIsSuitableField);
$ajaxOps->add($ajaxOpSetFieldsDef);
$ajaxOps->add($ajaxOpSetFieldsConstsDef);
$ajaxOps->add($ajaxOpSetFieldsDefWithoutExtKeys);
$ajaxOps->add($ajaxOpSqlServerImport);
$ajaxOps->add($ajaxOpTestConnection);
$ajaxOps->add($ajaxOpViewAllFieldsOp1);
$ajaxOps->add($ajaxOpViewAllFieldsOp2);
$ajaxOps->add($ajaxOpSqlServerCreateTable);
$ajaxOps->add($ajaxOpCheckIfKeyCollides);
$ajaxOps->add($ajaxOpViewAllTablesOp1);
$ajaxOps->add($ajaxOpViewAllTablesOp2);
$ajaxOps->add($ajaxOpViewAllRelationsOp1);
$ajaxOps->add($ajaxOpViewAllRelationsOp2);
$ajaxOps->add($ajaxOpRenameAllItems);
$ajaxOps->add($ajaxOpCheckIfKeyCollidesWithSonsKeys);
$ajaxOps->add($ajaxOpCheckIfIsDataSourceQuery);
$ajaxOps->add($ajaxOpViewAllQueriesOp1);
$ajaxOps->add($ajaxOpViewAllQueriesOp2);
$ajaxOps->add($ajaxOpSetSessionActiveApp);
$ajaxOps->add($ajaxOpExportQueryToCsv);
$ajaxOps->add($ajaxOpGetDbOpPars);
$ajaxOps->add($ajaxOpGetConnection);
$ajaxOps->add($ajaxOpSetConnection);
$ajaxOps->add($ajaxOpCreateConnectionsStruct);
$ajaxOps->add($ajaxOpViewAllConnectionsOp2);
$ajaxOps->add($ajaxOpCopyConnectionToDbPars);
$ajaxOps->add($ajaxOpViewAllAliasesOp1);
$ajaxOps->add($ajaxOpViewAllAliasesOp2);
$ajaxOps->add($ajaxOpSetAllAliases);
$ajaxOps->add($ajaxOpCheckIfAliasExists);
$ajaxOps->add($ajaxOpCheckIfTableExists);
$ajaxOps->add($ajaxOpViewTablesAndQueriesOp1);
$ajaxOps->add($ajaxOpViewTablesAndQueriesOp2);
$ajaxOps->add($ajaxOpViewTablesAndQueriesOp3);
$ajaxOps->add($ajaxOpGetNodeType);
$ajaxOps->add($ajaxOpSetAllTablesAndQueriesBinds);
$ajaxOps->add($ajaxOpCreateDbBinds);
$ajaxOps->add($ajaxOpUpdateBinds);
$ajaxOps->add($ajaxOpGetTableFromAlias);
$ajaxOps->add($ajaxOpGetLayouts);
$ajaxOps->add($ajaxOpLayoutsOp1);
$ajaxOps->add($ajaxOpLayoutsOp2);
$ajaxOps->add($ajaxOpSaveLayout);
$ajaxOps->add($ajaxOpCreateLayoutPreview);
$ajaxOps->add($ajaxOpGetLayout);
$ajaxOps->add($ajaxOpCreatePreview);
$ajaxOps->add($ajaxOpManageOp1);
$ajaxOps->add($ajaxOpManageOp2);
$ajaxOps->add($ajaxOpGetNamedInterfacesContainer);
$ajaxOps->add($ajaxOpGetAllTableFields);
$ajaxOps->add($ajaxOpGetAllAliasFields);
$ajaxOps->add($ajaxOpGetAllQueryFields);
$ajaxOps->add($ajaxOpGetAllModuleFields);
$ajaxOps->add($ajaxOpGetAllBindFields);
$ajaxOps->add($ajaxOpManageFieldsOp2);
$ajaxOps->add($ajaxOpManageFieldsOp1);
$ajaxOps->add($ajaxOpGetAllInterfacesOfPage);
$ajaxOps->add($ajaxOpFilterParentsInterfacesFiles);
$ajaxOps->add($ajaxOpGetInterfaceIds);
$ajaxOps->add($ajaxOpExport);
$ajaxOps->add($ajaxOpGetSingleMenus);
$ajaxOps->add($ajaxOpGetMultiMenus);
$ajaxOps->add($ajaxOpViewSingleMenuFieldsOp1);
$ajaxOps->add($ajaxOpViewSingleMenuFieldsOp2);
$ajaxOps->add($ajaxOpSetSingleMenu);
$ajaxOps->add($ajaxOpViewMultiMenuFieldsOp1);
$ajaxOps->add($ajaxOpViewMultiMenuFieldsOp2);
$ajaxOps->add($ajaxOpSetMultiMenu);
$ajaxOps->add($ajaxOpGetFreeInterfaceCanonicalName);
$ajaxOps->add($ajaxOpViewBindsOp1);
$ajaxOps->add($ajaxOpViewBindsOp2);
$ajaxOps->add($ajaxOpViewBindsOp3);
$ajaxOps->add($ajaxOpViewBindsOp4);
$ajaxOps->add($ajaxOpSetAllBinds);
$ajaxOps->add($ajaxOpRenameAliasName);
$ajaxOps->add($ajaxOpGetBindNodeName);
$ajaxOps->add($ajaxOpGetBindNodeType);
$ajaxOps->add($ajaxOpCheckIfNodeIsUsed);
$ajaxOps->add($ajaxOpCheckIfConnectionIsUsed);
$ajaxOps->add($ajaxOpViewBoundInterfacesOp2);
$ajaxOps->add($ajaxOpViewBoundInterfacesOp3);
$ajaxOps->add($ajaxOpSetAllBoundInterfaces);
$ajaxOps->add($ajaxOpCatalogOp2);
$ajaxOps->add($ajaxOpCatalogOp3);
$ajaxOps->add($ajaxOpCatalogOp4);
$ajaxOps->add($ajaxOpSetAllCatalogInterfaces);
$ajaxOps->add($ajaxOpGetInterfaceItemsNum);
$ajaxOps->add($ajaxOpIsInterfaceBusy);
$ajaxOps->add($ajaxOpExportChanges);
$ajaxOps->add($ajaxOpScanForItem);
$ajaxOps->add($ajaxOpManageAjaxOp1);
$ajaxOps->add($ajaxOpManageAjaxOp2);
$ajaxOps->add($ajaxOpSetAllAjaxOps);
$ajaxOps->add($ajaxOpManageAjaxClassesOp1);
$ajaxOps->add($ajaxOpManageAjaxClassesOp2);
$ajaxOps->add($ajaxOpSetAllAjaxOpsClasses);
$ajaxOps->add($ajaxOpGenerateAjaxOpsConfigurationFiles);
$ajaxOps->add($ajaxOpGenerateAjaxOpsClassesFiles);
$ajaxOps->add($ajaxOpPagesInterfacesExportChanges);
$ajaxOps->add($ajaxOpViewFormsSectionGridOp1);
$ajaxOps->add($ajaxOpSaveFormSection);
$ajaxOps->add($ajaxOpGetFormSections);
$ajaxOps->add($ajaxOpViewPdfTemplateGridOp1);
$ajaxOps->add($ajaxOpSavePdfTemplate);
$ajaxOps->add($ajaxOpGetPdfTemplates);
$ajaxOps->add($ajaxOpGetObjTypeByShortName);
$ajaxOps->add($ajaxOpGetFpdfIntProps);
$ajaxOps->add($ajaxOpGetPredInterfaces);
$ajaxOps->add($ajaxOpInterfaceExists);
$ajaxOps->add($ajaxOpCreatePdf);
$ajaxOps->add($ajaxOpDeleteFile2);
$ajaxOps->add($ajaxOpGetPredInterfaces2);
$ajaxOps->add($ajaxOpFileExists);
$ajaxOps->add($ajaxOpDojoInPreview);
$ajaxOps->add($ajaxOpCheckIfIsInRelation);
$ajaxOps->add($ajaxOpDeleteRelationsDefs);
$ajaxOps->add($ajaxOpGetPkKeyByTableName);
$ajaxOps->add($ajaxOpLogEnable);
$ajaxOps->add($ajaxOpTestIntFormat);
$ajaxOps->add($ajaxOpFixDbXmlFiles);



// Set Json enabled flags.
// SEZIONE Set Json enabled flags.
// Set Json enabled flags.
$ajaxOpJavascriptInjection->setIsJsonEnabled(false);
$ajaxOpLocalization->setIsJsonEnabled(true);
$ajaxOpTestDir->setIsJsonEnabled(false);
$ajaxOpGetScrollData->setIsJsonEnabled(false);
$ajaxOpGetSheetData->setIsJsonEnabled(false);
$ajaxOpGetFile->setIsJsonEnabled(false);
$ajaxOpOp1->setIsJsonEnabled(false);
$ajaxOpOp2->setIsJsonEnabled(false);
$ajaxOpOp3->setIsJsonEnabled(false);
$ajaxOpOp4->setIsJsonEnabled(false);
$ajaxOpOp5->setIsJsonEnabled(false);
$ajaxOpOp6->setIsJsonEnabled(false);
$ajaxOpOp7->setIsJsonEnabled(false);
$ajaxOpSendFile->setIsJsonEnabled(false);
$ajaxOpGetDbObjsDefProps->setIsJsonEnabled(false);
$ajaxOpSetDbObjsDefProps->setIsJsonEnabled(false);
$ajaxOpGetAllFieldsDefProps->setIsJsonEnabled(false);
$ajaxOpUnblockApp->setIsJsonEnabled(false);
$ajaxOpSetFieldsDefFieldsProps->setIsJsonEnabled(false);
$ajaxOpSetFieldsDefAllFieldsProps->setIsJsonEnabled(false);
$ajaxOpSetFieldsDefCandKeyFieldsProps->setIsJsonEnabled(false);
$ajaxOpSetFieldsDefExtKeyFieldsProps->setIsJsonEnabled(false);
$ajaxOpSet1NRelationsDefinitionProps->setIsJsonEnabled(false);
$ajaxOpGet1NRelations->setIsJsonEnabled(false);
$ajaxOpGetMNRelations->setIsJsonEnabled(false);
$ajaxOpSetMNRelationsDefinitionProps->setIsJsonEnabled(false);
$ajaxOpCreateDbStruct->setIsJsonEnabled(false);
$ajaxOpPostSendInterfaceData->setIsJsonEnabled(false);
$ajaxOpDeleteFile->setIsJsonEnabled(false);
$ajaxOpCreateFile->setIsJsonEnabled(false);
$ajaxOpRenameFile->setIsJsonEnabled(false);
$ajaxOpCreatePage->setIsJsonEnabled(false);
$ajaxOpGetQuery->setIsJsonEnabled(false);
$ajaxOpSetQuery->setIsJsonEnabled(false);
$ajaxOpSetAllQueries->setIsJsonEnabled(false);
$ajaxOpCreateQueriesStruct->setIsJsonEnabled(false);
$ajaxOpDumpAjaxOpsConstsFile->setIsJsonEnabled(false);
$ajaxOpAddAjaxOpsFromPhpArray->setIsJsonEnabled(false);
$ajaxOpGetParents->setIsJsonEnabled(false);
$ajaxOpCheckIfIs1NRelationFather->setIsJsonEnabled(false);
$ajaxOpCheckIfIs1NRelationFatherOf->setIsJsonEnabled(false);
$ajaxOpCheckIfIs1NRelation->setIsJsonEnabled(false);
$ajaxOpCheckIfExistMNRelationLinkTable->setIsJsonEnabled(false);
$ajaxOpGetFieldsDefProps->setIsJsonEnabled(false);
$ajaxOpGetCandKeyFieldsProps->setIsJsonEnabled(false);
$ajaxOpGetExtKeyFieldsProps->setIsJsonEnabled(false);
$ajaxOpGetPkKeyField->setIsJsonEnabled(false);
$ajaxOpSetPk->setIsJsonEnabled(false);
$ajaxOpCheckIfIsSuitablePkKey->setIsJsonEnabled(false);
$ajaxOpCheckIfIsSuitableField->setIsJsonEnabled(false);
$ajaxOpSetFieldsDef->setIsJsonEnabled(false);
$ajaxOpSetFieldsConstsDef->setIsJsonEnabled(false);
$ajaxOpSetFieldsDefWithoutExtKeys->setIsJsonEnabled(false);
$ajaxOpSqlServerImport->setIsJsonEnabled(false);
$ajaxOpTestConnection->setIsJsonEnabled(false);
$ajaxOpViewAllFieldsOp1->setIsJsonEnabled(false);
$ajaxOpViewAllFieldsOp2->setIsJsonEnabled(false);
$ajaxOpSqlServerCreateTable->setIsJsonEnabled(false);
$ajaxOpCheckIfKeyCollides->setIsJsonEnabled(false);
$ajaxOpViewAllTablesOp1->setIsJsonEnabled(false);
$ajaxOpViewAllTablesOp2->setIsJsonEnabled(false);
$ajaxOpViewAllRelationsOp1->setIsJsonEnabled(false);
$ajaxOpViewAllRelationsOp2->setIsJsonEnabled(false);
$ajaxOpRenameAllItems->setIsJsonEnabled(false);
$ajaxOpCheckIfKeyCollidesWithSonsKeys->setIsJsonEnabled(false);
$ajaxOpCheckIfIsDataSourceQuery->setIsJsonEnabled(false);
$ajaxOpViewAllQueriesOp1->setIsJsonEnabled(false);
$ajaxOpViewAllQueriesOp2->setIsJsonEnabled(false);
$ajaxOpSetSessionActiveApp->setIsJsonEnabled(false);
$ajaxOpExportQueryToCsv->setIsJsonEnabled(false);
$ajaxOpGetDbOpPars->setIsJsonEnabled(false);
$ajaxOpGetConnection->setIsJsonEnabled(false);
$ajaxOpSetConnection->setIsJsonEnabled(false);
$ajaxOpCreateConnectionsStruct->setIsJsonEnabled(false);
$ajaxOpViewAllConnectionsOp2->setIsJsonEnabled(false);
$ajaxOpCopyConnectionToDbPars->setIsJsonEnabled(false);
$ajaxOpViewAllAliasesOp1->setIsJsonEnabled(false);
$ajaxOpViewAllAliasesOp2->setIsJsonEnabled(false);
$ajaxOpSetAllAliases->setIsJsonEnabled(false);
$ajaxOpCheckIfAliasExists->setIsJsonEnabled(false);
$ajaxOpCheckIfTableExists->setIsJsonEnabled(false);
$ajaxOpViewTablesAndQueriesOp1->setIsJsonEnabled(false);
$ajaxOpViewTablesAndQueriesOp2->setIsJsonEnabled(false);
$ajaxOpGetNodeType->setIsJsonEnabled(false);
$ajaxOpSetAllTablesAndQueriesBinds->setIsJsonEnabled(false);
$ajaxOpCreateDbBinds->setIsJsonEnabled(false);
$ajaxOpUpdateBinds->setIsJsonEnabled(false);
$ajaxOpGetTableFromAlias->setIsJsonEnabled(false);
$ajaxOpGetLayouts->setIsJsonEnabled(false);
$ajaxOpLayoutsOp1->setIsJsonEnabled(false);
$ajaxOpLayoutsOp2->setIsJsonEnabled(false);
$ajaxOpSaveLayout->setIsJsonEnabled(false);
$ajaxOpCreateLayoutPreview->setIsJsonEnabled(false);
$ajaxOpGetLayout->setIsJsonEnabled(false);
$ajaxOpCreatePreview->setIsJsonEnabled(false);
$ajaxOpManageOp1->setIsJsonEnabled(false);
$ajaxOpManageOp2->setIsJsonEnabled(false);
$ajaxOpGetNamedInterfacesContainer->setIsJsonEnabled(false);
$ajaxOpGetAllTableFields->setIsJsonEnabled(false);
$ajaxOpGetAllAliasFields->setIsJsonEnabled(false);
$ajaxOpGetAllQueryFields->setIsJsonEnabled(false);
$ajaxOpGetAllModuleFields->setIsJsonEnabled(false);
$ajaxOpGetAllBindFields->setIsJsonEnabled(false);
$ajaxOpManageFieldsOp2->setIsJsonEnabled(false);
$ajaxOpManageFieldsOp1->setIsJsonEnabled(false);
$ajaxOpGetAllInterfacesOfPage->setIsJsonEnabled(false);
$ajaxOpFilterParentsInterfacesFiles->setIsJsonEnabled(false);
$ajaxOpGetInterfaceIds->setIsJsonEnabled(false);
$ajaxOpExport->setIsJsonEnabled(false);
$ajaxOpGetSingleMenus->setIsJsonEnabled(false);
$ajaxOpGetMultiMenus->setIsJsonEnabled(false);
$ajaxOpViewSingleMenuFieldsOp1->setIsJsonEnabled(false);
$ajaxOpViewSingleMenuFieldsOp2->setIsJsonEnabled(false);
$ajaxOpSetSingleMenu->setIsJsonEnabled(false);
$ajaxOpViewMultiMenuFieldsOp1->setIsJsonEnabled(false);
$ajaxOpViewMultiMenuFieldsOp2->setIsJsonEnabled(false);
$ajaxOpSetMultiMenu->setIsJsonEnabled(false);
$ajaxOpGetFreeInterfaceCanonicalName->setIsJsonEnabled(false);
$ajaxOpViewBindsOp1->setIsJsonEnabled(false);
$ajaxOpViewBindsOp2->setIsJsonEnabled(false);
$ajaxOpViewBindsOp3->setIsJsonEnabled(false);
$ajaxOpViewBindsOp4->setIsJsonEnabled(false);
$ajaxOpSetAllBinds->setIsJsonEnabled(false);
$ajaxOpRenameAliasName->setIsJsonEnabled(false);
$ajaxOpGetBindNodeName->setIsJsonEnabled(false);
$ajaxOpGetBindNodeType->setIsJsonEnabled(false);
$ajaxOpCheckIfNodeIsUsed->setIsJsonEnabled(false);
$ajaxOpCheckIfConnectionIsUsed->setIsJsonEnabled(false);
$ajaxOpViewBoundInterfacesOp2->setIsJsonEnabled(false);
$ajaxOpViewBoundInterfacesOp3->setIsJsonEnabled(false);
$ajaxOpSetAllBoundInterfaces->setIsJsonEnabled(false);
$ajaxOpCatalogOp2->setIsJsonEnabled(false);
$ajaxOpCatalogOp3->setIsJsonEnabled(false);
$ajaxOpCatalogOp4->setIsJsonEnabled(false);
$ajaxOpSetAllCatalogInterfaces->setIsJsonEnabled(false);
$ajaxOpGetInterfaceItemsNum->setIsJsonEnabled(false);
$ajaxOpIsInterfaceBusy->setIsJsonEnabled(false);
$ajaxOpExportChanges->setIsJsonEnabled(false);
$ajaxOpScanForItem->setIsJsonEnabled(false);
$ajaxOpManageAjaxOp1->setIsJsonEnabled(false);
$ajaxOpManageAjaxOp2->setIsJsonEnabled(false);
$ajaxOpSetAllAjaxOps->setIsJsonEnabled(false);
$ajaxOpManageAjaxClassesOp1->setIsJsonEnabled(false);
$ajaxOpManageAjaxClassesOp2->setIsJsonEnabled(false);
$ajaxOpSetAllAjaxOpsClasses->setIsJsonEnabled(false);
$ajaxOpGenerateAjaxOpsConfigurationFiles->setIsJsonEnabled(false);
$ajaxOpGenerateAjaxOpsClassesFiles->setIsJsonEnabled(false);
$ajaxOpPagesInterfacesExportChanges->setIsJsonEnabled(false);
$ajaxOpViewFormsSectionGridOp1->setIsJsonEnabled(false);
$ajaxOpSaveFormSection->setIsJsonEnabled(false);
$ajaxOpGetFormSections->setIsJsonEnabled(false);
$ajaxOpViewPdfTemplateGridOp1->setIsJsonEnabled(false);
$ajaxOpSavePdfTemplate->setIsJsonEnabled(false);
$ajaxOpGetPdfTemplates->setIsJsonEnabled(false);
$ajaxOpGetObjTypeByShortName->setIsJsonEnabled(false);
$ajaxOpGetFpdfIntProps->setIsJsonEnabled(false);
$ajaxOpGetPredInterfaces->setIsJsonEnabled(false);
$ajaxOpInterfaceExists->setIsJsonEnabled(false);
$ajaxOpCreatePdf->setIsJsonEnabled(false);
$ajaxOpDeleteFile2->setIsJsonEnabled(false);
$ajaxOpGetPredInterfaces2->setIsJsonEnabled(false);
$ajaxOpFileExists->setIsJsonEnabled(false);
$ajaxOpDojoInPreview->setIsJsonEnabled(false);
$ajaxOpCheckIfIsInRelation->setIsJsonEnabled(false);
$ajaxOpDeleteRelationsDefs->setIsJsonEnabled(false);
$ajaxOpGetPkKeyByTableName->setIsJsonEnabled(false);
$ajaxOpLogEnable->setIsJsonEnabled(false);
$ajaxOpTestIntFormat->setIsJsonEnabled(false);
$ajaxOpFixDbXmlFiles->setIsJsonEnabled(false);



// Generate ajax handler instance.
$ajaxHandler=new Cheope_ns_ajax_handler();

// Call ajax handler putData.
$ajaxHandler->setOpsContainer($ajaxOps);
$ajaxHandler->putData();

?>