<?
namespace Cheope_ns\fw;
require_once("cheope_ns_filesystem.const.php");
require_once("cheope_ns_generic.const.php");
require_once("class.const.php");
require_once("interfaces.const.php");
require_once("traits.const.php");

define(__NAMESPACE__ . '\OBJ_CLASS',"class");
define(__NAMESPACE__ . '\OBJ_FUNCTION',"function");
define(__NAMESPACE__ . '\OBJ_CONST',"const");
define(__NAMESPACE__ . '\OBJ_DEFINITION',"definition");
define(__NAMESPACE__ . '\OBJ_APPLICATION',"application");
define(__NAMESPACE__ . '\OBJ_INTERFACE',"interface");

define(__NAMESPACE__ . '\OBJ_FUNCTION_ABBR',"fun");
define(__NAMESPACE__ . '\OBJ_DEFINITION_ABBR',"def");
define(__NAMESPACE__ . '\OBJ_APPLICATION_ABBR',"app");
define(__NAMESPACE__ . '\OBJ_INTERFACE_ABBR',"int");
define(__NAMESPACE__ . '\OBJ_TRAIT_ABBR',"tra");

$globalObjs = array(namespace\OBJ_CLASS,namespace\OBJ_FUNCTION,
namespace\OBJ_CONST,namespace\OBJ_DEFINITION,namespace\OBJ_APPLICATION);

define(__NAMESPACE__ . '\CLASS_MOD_TYPE',namespace\OBJ_CLASS . VAR_SEP . 'mod');
define(__NAMESPACE__ . '\FUNCTION_LIB_MOD_TYPE',namespace\OBJ_FUNCTION . VAR_SEP . 'mod');
define(__NAMESPACE__ . '\CONST_LIB_MOD_TYPE',namespace\OBJ_CONST . VAR_SEP . 'mod');
define(__NAMESPACE__ . '\DEF_LIB_MOD_TYPE',namespace\OBJ_DEFINITION . VAR_SEP . 'mod');
define(__NAMESPACE__ . '\APP_MOD_TYPE',namespace\OBJ_APPLICATION . VAR_SEP . 'mod');

define(__NAMESPACE__ . '\FUNCTION_LIB_MOD_POSTFIX',namespace\OBJ_FUNCTION_ABBR);
define(__NAMESPACE__ . '\CONST_LIB_MOD_POSTFIX',namespace\OBJ_CONST);
define(__NAMESPACE__ . '\DEFINITION_MOD_POSTFIX',namespace\OBJ_DEFINITION_ABBR);
define(__NAMESPACE__ . '\CLASS_MOD_POSTFIX',namespace\OBJ_CLASS);
define(__NAMESPACE__ . '\INTERFACE_MOD_POSTFIX',namespace\OBJ_INTERFACE_ABBR);
define(__NAMESPACE__ . '\TRAIT_MOD_POSTFIX',namespace\OBJ_TRAIT_ABBR);
define(__NAMESPACE__ . '\DATA_PAGE_CLASS_MOD_POSTFIX','page');

define(__NAMESPACE__ . '\XML_CONST_MOD',"xml" . FILE_NAME_ELEMENTS_SEP .
namespace\CONST_LIB_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\CLASS_CONST_MOD',"class" . FILE_NAME_ELEMENTS_SEP . 
namespace\CONST_LIB_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\DB_CONST_MOD',"db" . FILE_NAME_ELEMENTS_SEP . 
namespace\CONST_LIB_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\HTTP_CONST_MOD',"http" . FILE_NAME_ELEMENTS_SEP . 
namespace\CONST_LIB_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\DB_OP_FUN_MOD',"db_op" . FILE_NAME_ELEMENTS_SEP . 
namespace\FUNCTION_LIB_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\ODBC_DB_OP_FUN_MOD',"odbc_db_op" . FILE_NAME_ELEMENTS_SEP . 
namespace\FUNCTION_LIB_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\SQLSRV_DB_OP_FUN_MOD',"sqlsrv_db_op" . FILE_NAME_ELEMENTS_SEP . 
namespace\FUNCTION_LIB_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\FILESYSTEM_FUN_MOD',"filesystem" . FILE_NAME_ELEMENTS_SEP . 
namespace\FUNCTION_LIB_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\FILESYSTEM_CONST_MOD',"filesystem" . FILE_NAME_ELEMENTS_SEP . 
namespace\CONST_LIB_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\FILESYSTEM_DEF_MOD',"filesystem" . FILE_NAME_ELEMENTS_SEP . 
namespace\DEFINITION_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\GENERIC_FUN_MOD',"generic" . FILE_NAME_ELEMENTS_SEP . 
namespace\FUNCTION_LIB_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\GENERIC_CONST_MOD',"generic" . FILE_NAME_ELEMENTS_SEP . 
namespace\CONST_LIB_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\HTML_FUN_MOD',"html" . FILE_NAME_ELEMENTS_SEP . 
namespace\FUNCTION_LIB_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\FCKEDITOR_FUN_MOD',"fckeditor" . FILE_NAME_ELEMENTS_SEP .
namespace\FUNCTION_LIB_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\HTML_CONST_MOD',"html" . FILE_NAME_ELEMENTS_SEP . 
namespace\CONST_LIB_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\JAVASCRIPT_FUN_MOD',"javascript" . FILE_NAME_ELEMENTS_SEP . 
namespace\FUNCTION_LIB_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\JAVASCRIPT_CONST_MOD',"javascript" . FILE_NAME_ELEMENTS_SEP . 
namespace\CONST_LIB_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\SQL_SERVER_FUN_MOD',"sql_server" . FILE_NAME_ELEMENTS_SEP . 
namespace\FUNCTION_LIB_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\SQL_SERVER_CONST_MOD',"sql_server" . FILE_NAME_ELEMENTS_SEP . 
namespace\CONST_LIB_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\ODBC_CONST_MOD',"odbc" . FILE_NAME_ELEMENTS_SEP . 
namespace\CONST_LIB_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\MYSQL_FUN_MOD',"mySql" . FILE_NAME_ELEMENTS_SEP . 
namespace\FUNCTION_LIB_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\MYSQL_CONST_MOD',"mySql" . FILE_NAME_ELEMENTS_SEP . 
namespace\CONST_LIB_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\PARSER_CONST_MOD',"parser" . FILE_NAME_ELEMENTS_SEP . 
namespace\CONST_LIB_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\LEXER_CONST_MOD',"lexer" . FILE_NAME_ELEMENTS_SEP . 
namespace\CONST_LIB_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\RIC_SQL_2_DEF_MOD',"ric_sql_2" . FILE_NAME_ELEMENTS_SEP . 
namespace\DEFINITION_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\PHP_ARRAYS_DEF_MOD',"php_arrays" . FILE_NAME_ELEMENTS_SEP . 
namespace\DEFINITION_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\AJAX_HANDLER_MOD',"ajax_handler" . 
 FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\ROOT_CONST_MOD',"root" . FILE_NAME_ELEMENTS_SEP . namespace\CONST_LIB_MOD_POSTFIX . 
FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\ROOT_FUN_MOD',"root" . FILE_NAME_ELEMENTS_SEP . namespace\FUNCTION_LIB_MOD_POSTFIX . 
FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\ROOT_DEF_MOD',"root" . FILE_NAME_ELEMENTS_SEP . namespace\DEFINITION_MOD_POSTFIX . 
FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\STRUCT_FUN_MOD',"struct" . FILE_NAME_ELEMENTS_SEP . 
namespace\FUNCTION_LIB_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE); 
define(__NAMESPACE__ . '\DB_ITEM_CONST_MOD',"db_item" . FILE_NAME_ELEMENTS_SEP . namespace\CONST_LIB_MOD_POSTFIX .
FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\DB_REL_CONST_MOD',"db_rel" . FILE_NAME_ELEMENTS_SEP . 
namespace\CONST_LIB_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\DYN_PAGE_LOADER_DEF_MOD',"dyn_page_loader" . FILE_NAME_ELEMENTS_SEP . 
namespace\DEFINITION_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\LOADER_MOD',"loader" . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\ERROR_HANDLER_DEF_MOD',"error_handler" . FILE_NAME_ELEMENTS_SEP .
namespace\DEFINITION_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);

define(__NAMESPACE__ . '\STD_DB_OP_FUN_MOD',"std_db_op" . FILE_NAME_ELEMENTS_SEP . 
namespace\FUNCTION_LIB_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\STD_SQLSRV_DB_OP_FUN_MOD',"std_sqlsrv_db_op" . FILE_NAME_ELEMENTS_SEP . 
namespace\FUNCTION_LIB_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\STD_ODBC_DB_OP_FUN_MOD',"std_odbc_db_op" . FILE_NAME_ELEMENTS_SEP . 
namespace\FUNCTION_LIB_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\INTERFACE_DATA_DOMAINS_CONST_MOD',"interface_data_domains" . 
FILE_NAME_ELEMENTS_SEP . namespace\CONST_LIB_MOD_POSTFIX . 
FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\ITEMS_REQUIRE_ONCES_DEF_MOD',"items_require_onces" .
FILE_NAME_ELEMENTS_SEP . namespace\DEFINITION_MOD_POSTFIX . 
FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);


define(__NAMESPACE__ . '\DB_NODE_CLASS_MOD',DB_NODE_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\DB_REL_CLASS_MOD',DB_REL_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\GNODE_CLASS_MOD',GNODE_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\GGRAPH_CLASS_MOD',GGRAPH_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\GGRAPH_ITERATOR_CLASS_MOD',GGRAPH_ITERATOR_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\AJAXOP_CLASS_MOD',AJAXOP_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\AJAXOPS_CONTAINER_CLASS_MOD',AJAXOPS_CONTAINER_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\GENERIC_ITERATOR_CLASS_MOD',GENERIC_ITERATOR_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\GENERIC_CONTAINER_CLASS_MOD',GENERIC_CONTAINER_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\CONTAINER_ASSOCIATIVE_CLASS_MOD',CONTAINER_ASSOCIATIVE_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\INT_FIELD_CLASS_MOD',INT_FIELD_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\INT_FIELDS_CONTAINER_CLASS_MOD',INT_FIELDS_CONTAINER_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\INTERFACES_CONTAINER_CLASS_MOD',INTERFACES_CONTAINER_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\INTERFACE_DATA_DOMAINS_CLASS_MOD',"Interface_data_domains" . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\GENERIC_INTERFACE_CLASS_MOD',GENERIC_INTERFACE_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\DATA_INTERFACE_CLASS_MOD',DATA_INTERFACE_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\FORMATTED_INTERFACE_CLASS_MOD',FORMATTED_INTERFACE_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\CACHED_DATA_INTERFACE_CLASS_MOD',CACHED_DATA_INTERFACE_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\HTML_DATA_INTERFACE_CLASS_MOD',HTML_DATA_INTERFACE_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\XML_DATA_INTERFACE_CLASS_MOD',XML_DATA_INTERFACE_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\XML_DOCUMENT_CLASS_MOD',XML_DOCUMENT_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\HTML_CACHED_DATA_INTERFACE_CLASS_MOD',HTML_CACHED_DATA_INTERFACE_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\HTML_PAGE_CLASS_MOD',HTML_PAGE_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\HTML_FORMATTED_INTERFACE_CLASS_MOD',HTML_FORMATTED_INTERFACE_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\XML_FORMATTED_INTERFACE_CLASS_MOD',XML_FORMATTED_INTERFACE_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\DB_ITEM_CLASS_MOD',DB_ITEM_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\DB_QUERY_CLASS_MOD',DB_QUERY_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\LEXER_3_CLASS_MOD',LEXER_3_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\PARSER_CLASS_MOD',PARSER_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\RIC_SQL_2_PARSER_GRAMMAR_RULES_CLASS_MOD',RIC_SQL_2_PARSER_GRAMMAR_RULES_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\TOKEN_CLASS_MOD',TOKEN_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\TOKENS_CONTAINER_CLASS_MOD',TOKENS_CONTAINER_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\LEX_RULES_CONTAINER_CLASS_MOD',LEX_RULES_CONTAINER_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\LEX_RULE_CLASS_MOD',"Lex_rule" . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\PARSER_GRAMMAR_RULES_CONTAINER_CLASS_MOD',PARSER_GRAMMAR_RULES_CONTAINER_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\PARSER_GRAMMAR_RULE_CLASS_MOD',PARSER_GRAMMAR_RULE_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\HTML_TAG_CLASS_MOD',HTML_TAG_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\HTML_TAGS_CLASS_MOD',HTML_TAGS_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE );
define(__NAMESPACE__ . '\HTML_FRAGMENT_CLASS_MOD',HTML_FRAGMENT_CLASS  . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\HTML_DATA_TEMPLATE_CLASS_MOD',HTML_DATA_TEMPLATE_CLASS  . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\HTML_GENERIC_DATA_TEMPLATE_CLASS_MOD',HTML_GENERIC_DATA_TEMPLATE_CLASS  . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\XML_DATA_TEMPLATE_CLASS_MOD',XML_DATA_TEMPLATE_CLASS  . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\HTML_BUTTON_TAG_CLASS_MOD',HTML_BUTTON_TAG_CLASS  . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\HTML_DIV_TAG_CLASS_MOD',HTML_DIV_TAG_CLASS  . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\HTML_BR_TAG_CLASS_MOD',HTML_BR_TAG_CLASS  . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\HTML_P_TAG_CLASS_MOD',HTML_P_TAG_CLASS  . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\HTML_SCRIPT_TAG_CLASS_MOD',HTML_SCRIPT_TAG_CLASS  . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\HTML_INPUT_CTRL_CLASS_MOD',HTML_INPUT_CTRL_CLASS  . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\HTML_SPAN_TAG_CLASS_MOD',HTML_SPAN_TAG_CLASS  . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\XML_INTERFACE_SERIALIZER_CLASS_MOD',XML_INTERFACE_SERIALIZER_CLASS  . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\XML_INTERFACE_SERIALIZER_CREATEINTERFACEFROMSTRINGCLASSES_CLASS_MOD',"Xml_interface_serializer_createInterfaceFromStringClasses" . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\XML_INTERFACE_SERIALIZER_LOADITEMSCLASSES_CLASS_MOD',"Xml_interface_serializer_loadItemsClasses" . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\XML_INTERFACE_SERIALIZER_LOADDATACLASSES_CLASS_MOD',"Xml_interface_serializer_loadDataClasses" . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\XML_ITEMS_LOADDATACLASSES_CLASS_MOD',"Xml_items_loadDataClasses" . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\INPUTCTRL_PUTINPUTCTRLCLASSES_MOD',"InputCtrl_putInputCtrlClasses" . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\INPUTCTRL_PUTDOJOINPUTCTRLCLASSES_MOD',"InputCtrl_putDojoInputCtrlClasses" . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\XML_SERIALIZER_CLASS_MOD',XML_SERIALIZER_CLASS  . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\JSON_SERIALIZER_CLASS_MOD',JSON_SERIALIZER_CLASS  . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\SERIALIZER_CLASS_MOD',SERIALIZER_CLASS  . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\PHP_FRAGMENT_CLASS_MOD',PHP_FRAGMENT_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\PHP_DATA_FRAGMENT_CLASS_MOD',PHP_DATA_FRAGMENT_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\PHP_SWITCH_STRUCT_CLASS_MOD',PHP_SWITCH_STRUCT_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\XML_TAG_BUILDER_CLASS_MOD',XML_TAG_BUILDER_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\XML_FILTER_CLASS_MOD',XML_FILTER_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\XML_REV_FILTER_CLASS_MOD',XML_REV_FILTER_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\JSON_FILTER_CLASS_MOD',JSON_FILTER_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\JSON_REV_FILTER_CLASS_MOD',JSON_REV_FILTER_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\FILTER_CLASS_MOD',FILTER_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\JAVASCRIPT_DATA_TEMPLATE_CLASS_MOD',JAVASCRIPT_DATA_TEMPLATE_CLASS . 
FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE); 
define(__NAMESPACE__ . '\JAVASCRIPT_DATA_FRAGMENT_CLASS_MOD',JAVASCRIPT_DATA_FRAGMENT_CLASS . 
FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE); 
define(__NAMESPACE__ . '\JAVASCRIPT_DATA_TXTEDITOR_CLASS_MOD',JAVASCRIPT_DATA_TXTEDITOR_CLASS . 
FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE); 
define(__NAMESPACE__ . '\JAVASCRIPT_FRAGMENT_CLASS_MOD',JAVASCRIPT_FRAGMENT_CLASS . 
FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\HTML_FRAMESET_PAGE_CLASS_MOD',HTML_FRAMESET_PAGE_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\HTML_FRAMESET_TAG_CLASS_MOD',HTML_FRAMESET_TAG_CLASS  . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\HTML_FRAME_TAG_CLASS_MOD',HTML_FRAME_TAG_CLASS  . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\ITEM_STACK_CLASS_MOD',ITEM_STACK_CLASS  . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\ITEM_CLASS_MOD',ITEM_CLASS  . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\DUMPER_CLASS_MOD',DUMPER_CLASS  . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\MEMORY_DUMPER_CLASS_MOD',MEMORY_DUMPER_CLASS  . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\ECHO_DUMPER_CLASS_MOD',ECHO_DUMPER_CLASS  . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\FILE_DUMPER_CLASS_MOD',FILE_DUMPER_CLASS  . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\ARRAY_ITEM_CLASS_MOD',ARRAY_ITEM_CLASS  . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\STRING_ITEM_CLASS_MOD',STRING_ITEM_CLASS  . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\ARG_ITEM_CLASS_MOD',ARG_ITEM_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\ASSOCIATIVE_ITEM_CLASS_MOD',ASSOCIATIVE_ITEM_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\CONSTRUCTOR_CALL_ITEM_CLASS_MOD', CONSTRUCTOR_CALL_ITEM_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\CONST_ITEM_CLASS_MOD',CONST_ITEM_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\DEF_ITEM_CLASS_MOD' , DEF_ITEM_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\METHOD_CALL_ITEM_CLASS_MOD',METHOD_CALL_ITEM_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\SECTION_ITEM_CLASS_MOD',SECTION_ITEM_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\SECTIONS_ITEM_CLASS_MOD', SECTIONS_ITEM_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\VAR_ITEM_CLASS_MOD', VAR_ITEM_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\FUNCTION_CALL_ITEM_CLASS_MOD', FUNCTION_CALL_ITEM_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\COND_ITEM_CLASS_MOD',COND_ITEM_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\IF_ELSE_ITEM_CLASS_MOD',IF_ELSE_ITEM_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\BLOCK_DEF_ITEM_CLASS_MOD',BLOCK_DEF_ITEM_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\CONCAT_ITEM_CLASS_MOD',CONCAT_ITEM_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\CLASS_DEF_ITEM_CLASS_MOD',CLASS_DEF_ITEM_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\CLASS_PROP_ITEM_CLASS_MOD',CLASS_PROP_ITEM_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\CLASS_VAR_ITEM_CLASS_MOD',CLASS_VAR_ITEM_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\ARGS_LIST_ITEM_CLASS_MOD',ARGS_LIST_ITEM_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\FUNCTION_DEF_ITEM_CLASS_MOD', FUNCTION_DEF_ITEM_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\REF_ITEM_CLASS_MOD', REF_ITEM_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\EXPR_ITEM_CLASS_MOD', EXPR_ITEM_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\CODE_ITEM_CLASS_MOD',CODE_ITEM_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\NAMESPACE_ITEM_CLASS_MOD',NAMESPACE_ITEM_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\COMMENT_ITEM_CLASS_MOD',COMMENT_ITEM_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\ITEMS_FACTORY_CLASS_MOD' , ITEMS_FACTORY_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\XML_ITEMS_SERIALIZER_CLASS_MOD', XML_ITEMS_SERIALIZER_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\STACK_CLASS_MOD',STACK_CLASS  . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\HTML_WRITER_CLASS_MOD',HTML_WRITER_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\HTML_INTERFACE_DECORATOR_CLASS_MOD',HTML_INTERFACE_DECORATOR_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\HTML_FIELDSET_DECORATOR_CLASS_MOD',HTML_FIELDSET_DECORATOR_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\HTML_UL_TAG_CLASS_MOD',HTML_UL_TAG_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\HTML_OL_TAG_CLASS_MOD',HTML_OL_TAG_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\HTML_LI_TAG_CLASS_MOD',HTML_LI_TAG_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\HTML_IMG_TAG_CLASS_MOD',HTML_IMG_TAG_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\QUERIES_CONTAINER_CLASS_MOD',QUERIES_CONTAINER_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\QUERIES_ITERATOR_CLASS_MOD', QUERIES_ITERATOR_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\XML_NODE_CLASS_MOD',XML_NODE_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\JSON_NODE_CLASS_MOD',JSON_NODE_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\PROFILER_CLASS_MOD',PROFILER_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\HTTP_CLIENT_CLASS_MOD',HTTP_CLIENT_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\FCKEDITOR_CLASS_MOD',FCKEDITOR_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
//define('JPGRAPH_CLASS_MOD',JPGRAPH_CLASS . FILE_NAME_ELEMENTS_SEP . CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\JPGRAPH_BAR_CLASS_MOD',JPGRAPH_BAR_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\OBJ_CACHE_CLASS_MOD',OBJ_CACHE_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\HTML_INPUT_TAG_CLASS_MOD',HTML_INPUT_TAG_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\HTML_TEXTAREA_TAG_CLASS_MOD',HTML_TEXTAREA_TAG_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\HTML_SELECT_TAG_CLASS_MOD',HTML_SELECT_TAG_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE); 
define(__NAMESPACE__ . '\HTML_OPTION_TAG_CLASS_MOD',HTML_OPTION_TAG_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE); 
define(__NAMESPACE__ . '\HTML_DATA_FILE_TEMPLATE_CLASS_MOD',HTML_DATA_FILE_TEMPLATE_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\SERIALIZABLE_NODE_CLASS_MOD',SERIALIZABLE_NODE_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\HTML_FORM_TAG_CLASS_MOD',HTML_FORM_TAG_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\HTML_LABEL_TAG_CLASS_MOD',HTML_LABEL_TAG_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\HTML_B_TAG_CLASS_MOD',HTML_B_TAG_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\HTML_HR_TAG_CLASS_MOD',HTML_HR_TAG_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\GENERIC_DB_OP_CLASS_MOD',GENERIC_DB_OP_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE); 
define(__NAMESPACE__ . '\ODBC_DB_OP_CLASS_MOD',ODBC_DB_OP_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE); 
define(__NAMESPACE__ . '\SQLSRV_DB_OP_CLASS_MOD',SQLSRV_DB_OP_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE); 
define(__NAMESPACE__ . '\DYN_PAGE_COMP_HANDLER_CLASS_MOD',DYN_PAGE_COMP_HANDLER_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE); 
define(__NAMESPACE__ . '\DYN_PAGE_LOADER_PARSER_GRAMMAR_RULES_CLASS_MOD',DYN_PAGE_LOADER_PARSER_GRAMMAR_RULES_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE); 
define(__NAMESPACE__ . '\DB_ITEM_PROCESSOR_CLASS_MOD',DB_ITEM_PROCESSOR_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\PHPMSGSGEN_CLASS_MOD',PHPMSGSGEN_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\XML_DB_MODEL_CLASS_MOD',XML_DB_MODEL_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\DB_OPS_CONTAINER_CLASS_MOD',DB_OPS_CONTAINER_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\CLASSES_INFO_CLASS_MOD',CLASSES_INFO_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\INTERFACES_INFO_CLASS_MOD',INTERFACES_INFO_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\CLONE_CALL_ITEM_CLASS_MOD',CLONE_CALL_ITEM_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE); 
define(__NAMESPACE__ . '\HTML_FILE_FRAGMENT_CLASS_MOD',HTML_FILE_FRAGMENT_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\DB_NODES_CONTAINER_CLASS_MOD',DB_NODES_CONTAINER_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\DB_NODES_ITERATOR_CLASS_MOD',DB_NODES_ITERATOR_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\DB_ITEMS_CONTAINER_CLASS_MOD',DB_ITEMS_CONTAINER_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\DB_ITEMS_ITERATOR_CLASS_MOD',DB_ITEMS_ITERATOR_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\XML_INTERFACE_FILE_ANALYZER_CLASS_MOD',XML_INTERFACE_FILE_ANALYZER_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\UPLOADED_FILE_MANAGER_CLASS_MOD',UPLOADED_FILE_MANAGER_CLASS . FILE_NAME_ELEMENTS_SEP  . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\INTERFACES_MODEL_CLASS_MOD',INTERFACES_MODEL_CLASS . FILE_NAME_ELEMENTS_SEP  . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\HTML_A_TAG_CLASS_MOD',HTML_A_TAG_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\PHP_FRAGMENT_FREE_CLASS_MOD',PHP_FRAGMENT_FREE_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\PHP_ARRAYS_PARSER_GRAMMAR_RULES_CLASS_MOD',PHP_ARRAYS_PARSER_GRAMMAR_RULES_CLASS . FILE_NAME_ELEMENTS_SEP . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\INTERFACE_AS_STRING_CLASS_MOD',INTERFACE_AS_STRING_CLASS . FILE_NAME_ELEMENTS_SEP  . namespace\CLASS_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);

define(__NAMESPACE__ . '\AUTOLOAD_INT_MOD', AUTOLOAD_INT . FILE_NAME_ELEMENTS_SEP . namespace\INTERFACE_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\BOOTSTRAP_INT_MOD', BOOTSTRAP_INT . FILE_NAME_ELEMENTS_SEP . namespace\INTERFACE_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\CONTAINER_INT_MOD', CONTAINER_INT . FILE_NAME_ELEMENTS_SEP . namespace\INTERFACE_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\CONTENT_INT_MOD', CONTENT_INT . FILE_NAME_ELEMENTS_SEP . namespace\INTERFACE_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\DECORATOR_INT_MOD', DECORATOR_INT . FILE_NAME_ELEMENTS_SEP . namespace\INTERFACE_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\DYN_PAGE_INT_MOD', DYN_PAGE_INT . FILE_NAME_ELEMENTS_SEP . namespace\INTERFACE_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\EXECUTABLE_INT_MOD', EXECUTABLE_INT . FILE_NAME_ELEMENTS_SEP . namespace\INTERFACE_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\EXECUTABLE_1_INT_MOD', EXECUTABLE_1_INT . FILE_NAME_ELEMENTS_SEP . namespace\INTERFACE_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\EXECUTABLE_2_INT_MOD', EXECUTABLE_2_INT . FILE_NAME_ELEMENTS_SEP . namespace\INTERFACE_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\EXECUTABLE_3_INT_MOD', EXECUTABLE_3_INT . FILE_NAME_ELEMENTS_SEP . namespace\INTERFACE_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\EXECUTABLE_4_INT_MOD', EXECUTABLE_4_INT . FILE_NAME_ELEMENTS_SEP . namespace\INTERFACE_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\EXECUTABLE_5_INT_MOD', EXECUTABLE_5_INT . FILE_NAME_ELEMENTS_SEP . namespace\INTERFACE_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\EXECUTABLE_6_INT_MOD', EXECUTABLE_6_INT . FILE_NAME_ELEMENTS_SEP . namespace\INTERFACE_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\EXECUTABLE_7_INT_MOD', EXECUTABLE_7_INT . FILE_NAME_ELEMENTS_SEP . namespace\INTERFACE_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\EXECUTABLE_8_INT_MOD', EXECUTABLE_8_INT . FILE_NAME_ELEMENTS_SEP . namespace\INTERFACE_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\EXECUTABLE_9_INT_MOD', EXECUTABLE_9_INT . FILE_NAME_ELEMENTS_SEP . namespace\INTERFACE_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\FACTORY_1_INT_MOD', FACTORY_1_INT . FILE_NAME_ELEMENTS_SEP . namespace\INTERFACE_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\FACTORY_2_INT_MOD', FACTORY_2_INT . FILE_NAME_ELEMENTS_SEP . namespace\INTERFACE_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\FACTORY_3_INT_MOD', FACTORY_3_INT . FILE_NAME_ELEMENTS_SEP . namespace\INTERFACE_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\FACTORY_4_INT_MOD', FACTORY_4_INT . FILE_NAME_ELEMENTS_SEP . namespace\INTERFACE_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\FACTORY_5_INT_MOD', FACTORY_5_INT . FILE_NAME_ELEMENTS_SEP . namespace\INTERFACE_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\FACTORY_6_INT_MOD', FACTORY_6_INT . FILE_NAME_ELEMENTS_SEP . namespace\INTERFACE_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\FACTORY_7_INT_MOD', FACTORY_7_INT . FILE_NAME_ELEMENTS_SEP . namespace\INTERFACE_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\FACTORY_8_INT_MOD', FACTORY_8_INT . FILE_NAME_ELEMENTS_SEP . namespace\INTERFACE_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\FACTORY_9_INT_MOD', FACTORY_9_INT . FILE_NAME_ELEMENTS_SEP . namespace\INTERFACE_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\FACTORY_10_INT_MOD', FACTORY_10_INT . FILE_NAME_ELEMENTS_SEP . namespace\INTERFACE_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\FACTORY_11_INT_MOD', FACTORY_11_INT . FILE_NAME_ELEMENTS_SEP . namespace\INTERFACE_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\GRAPHITER_INT_MOD', GRAPHITER_INT . FILE_NAME_ELEMENTS_SEP . namespace\INTERFACE_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\INIT_1_INT_MOD', INIT_1_INT . FILE_NAME_ELEMENTS_SEP . namespace\INTERFACE_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\INIT_2_INT_MOD', INIT_2_INT . FILE_NAME_ELEMENTS_SEP . namespace\INTERFACE_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\INIT_3_INT_MOD', INIT_3_INT . FILE_NAME_ELEMENTS_SEP . namespace\INTERFACE_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\OUTPUT_INT_MOD', OUTPUT_INT . FILE_NAME_ELEMENTS_SEP . namespace\INTERFACE_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\STRINGABLE_INT_MOD', STRINGABLE_INT . FILE_NAME_ELEMENTS_SEP . namespace\INTERFACE_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\JAVASCRIPT_INT_MOD', JAVASCRIPT_INT . FILE_NAME_ELEMENTS_SEP . namespace\INTERFACE_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\IITEM_INT_MOD', IITEM_INT . FILE_NAME_ELEMENTS_SEP . namespace\INTERFACE_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\SERIALIZABLE_INT_MOD', SERIALIZABLE_INT . FILE_NAME_ELEMENTS_SEP . namespace\INTERFACE_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\ITEMS_INT_MOD', ITEMS_INT . FILE_NAME_ELEMENTS_SEP . namespace\INTERFACE_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\STANDARD_INT_MOD', STANDARD_INT . FILE_NAME_ELEMENTS_SEP . namespace\INTERFACE_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\CSS_INT_MOD', CSS_INT . FILE_NAME_ELEMENTS_SEP . namespace\INTERFACE_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\JQUERY_INT_MOD', JQUERY_INT . FILE_NAME_ELEMENTS_SEP . namespace\INTERFACE_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\DOJO_INT_MOD', DOJO_INT . FILE_NAME_ELEMENTS_SEP . namespace\INTERFACE_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\HTML_TEMPLATE_INT_MOD', HTML_TEMPLATE_INT . FILE_NAME_ELEMENTS_SEP . namespace\INTERFACE_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\CREATOR_TRA_MOD', CREATOR_TRA . FILE_NAME_ELEMENTS_SEP . namespace\TRAIT_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\CALLER_TRA_MOD', CALLER_TRA . FILE_NAME_ELEMENTS_SEP . namespace\TRAIT_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);
define(__NAMESPACE__ . '\SERIALIZE_PROPS_TRA_MOD',SERIALIZE_PROPS_TRA . FILE_NAME_ELEMENTS_SEP . namespace\TRAIT_MOD_POSTFIX . FILE_NAME_ELEMENTS_SEP . APP_LANGUAGE);

$stdModules = array(namespace\XML_CONST_MOD,namespace\CLASS_CONST_MOD,namespace\DB_CONST_MOD,
namespace\HTTP_CONST_MOD,
namespace\FILESYSTEM_FUN_MOD,namespace\FILESYSTEM_CONST_MOD,namespace\FILESYSTEM_DEF_MOD,
namespace\GENERIC_FUN_MOD,namespace\GENERIC_CONST_MOD,namespace\FCKEDITOR_FUN_MOD,
namespace\HTML_FUN_MOD,namespace\HTML_CONST_MOD,
namespace\JAVASCRIPT_FUN_MOD,namespace\JAVASCRIPT_CONST_MOD,
namespace\SQL_SERVER_FUN_MOD,namespace\SQL_SERVER_CONST_MOD,namespace\ODBC_CONST_MOD,
namespace\MYSQL_FUN_MOD,namespace\MYSQL_CONST_MOD,
namespace\PARSER_CONST_MOD,namespace\LEXER_CONST_MOD,namespace\RIC_SQL_2_DEF_MOD,
namespace\STRUCT_FUN_MOD,namespace\INTERFACE_DATA_DOMAINS_CONST_MOD,
namespace\DB_NODE_CLASS_MOD,namespace\DB_REL_CLASS_MOD,namespace\DB_REL_CONST_MOD,
namespace\GNODE_CLASS_MOD,namespace\GGRAPH_CLASS_MOD,
namespace\GGRAPH_ITERATOR_CLASS_MOD,
namespace\AJAXOP_CLASS_MOD,namespace\AJAXOPS_CONTAINER_CLASS_MOD,
namespace\GENERIC_ITERATOR_CLASS_MOD,
namespace\INT_FIELD_CLASS_MOD,
namespace\INT_FIELDS_CONTAINER_CLASS_MOD,
namespace\INTERFACES_CONTAINER_CLASS_MOD,
namespace\INTERFACE_DATA_DOMAINS_CLASS_MOD,
namespace\GENERIC_INTERFACE_CLASS_MOD,namespace\DATA_INTERFACE_CLASS_MOD,
namespace\FORMATTED_INTERFACE_CLASS_MOD,
namespace\CACHED_DATA_INTERFACE_CLASS_MOD,
namespace\GENERIC_CONTAINER_CLASS_MOD,namespace\CONTAINER_ASSOCIATIVE_CLASS_MOD,
namespace\HTML_DATA_INTERFACE_CLASS_MOD,namespace\HTML_CACHED_DATA_INTERFACE_CLASS_MOD,
namespace\XML_DATA_INTERFACE_CLASS_MOD,
namespace\XML_DOCUMENT_CLASS_MOD,
namespace\HTML_PAGE_CLASS_MOD,
namespace\HTML_FORMATTED_INTERFACE_CLASS_MOD,namespace\XML_FORMATTED_INTERFACE_CLASS_MOD,
namespace\DB_ITEM_CLASS_MOD,namespace\DB_QUERY_CLASS_MOD,
namespace\LEXER_3_CLASS_MOD,namespace\PARSER_CLASS_MOD,
namespace\RIC_SQL_2_PARSER_GRAMMAR_RULES_CLASS_MOD,
namespace\TOKEN_CLASS_MOD,namespace\TOKENS_CONTAINER_CLASS_MOD,
namespace\LEX_RULES_CONTAINER_CLASS_MOD,namespace\LEX_RULE_CLASS_MOD,
namespace\PARSER_GRAMMAR_RULES_CONTAINER_CLASS_MOD,
namespace\PARSER_GRAMMAR_RULE_CLASS_MOD,
namespace\PHP_ARRAYS_DEF_MOD,
namespace\HTML_TAG_CLASS_MOD,namespace\HTML_TAGS_CLASS_MOD,
namespace\HTML_FRAGMENT_CLASS_MOD,namespace\HTML_DATA_TEMPLATE_CLASS_MOD,
namespace\HTML_GENERIC_DATA_TEMPLATE_CLASS_MOD,
namespace\XML_DATA_TEMPLATE_CLASS_MOD,
namespace\HTML_BUTTON_TAG_CLASS_MOD,namespace\HTML_DIV_TAG_CLASS_MOD,
namespace\HTML_BR_TAG_CLASS_MOD,namespace\HTML_P_TAG_CLASS_MOD,
namespace\HTML_SCRIPT_TAG_CLASS_MOD,namespace\HTML_INPUT_CTRL_CLASS_MOD,
namespace\HTML_SPAN_TAG_CLASS_MOD,namespace\HTML_FILE_FRAGMENT_CLASS_MOD,
namespace\XML_INTERFACE_SERIALIZER_CLASS_MOD,
namespace\XML_INTERFACE_SERIALIZER_CREATEINTERFACEFROMSTRINGCLASSES_CLASS_MOD,
namespace\XML_INTERFACE_SERIALIZER_LOADITEMSCLASSES_CLASS_MOD,
namespace\XML_INTERFACE_SERIALIZER_LOADDATACLASSES_CLASS_MOD,
namespace\XML_ITEMS_LOADDATACLASSES_CLASS_MOD,
namespace\INPUTCTRL_PUTINPUTCTRLCLASSES_MOD,
namespace\INPUTCTRL_PUTDOJOINPUTCTRLCLASSES_MOD,
namespace\XML_SERIALIZER_CLASS_MOD,namespace\JSON_SERIALIZER_CLASS_MOD,
namespace\SERIALIZER_CLASS_MOD,namespace\PHP_FRAGMENT_CLASS_MOD,
namespace\PHP_DATA_FRAGMENT_CLASS_MOD,namespace\PHP_SWITCH_STRUCT_CLASS_MOD,
namespace\XML_TAG_BUILDER_CLASS_MOD,
namespace\XML_FILTER_CLASS_MOD,namespace\XML_REV_FILTER_CLASS_MOD,
namespace\JSON_FILTER_CLASS_MOD,namespace\JSON_REV_FILTER_CLASS_MOD,namespace\FILTER_CLASS_MOD,
namespace\JAVASCRIPT_DATA_TEMPLATE_CLASS_MOD,namespace\JAVASCRIPT_DATA_FRAGMENT_CLASS_MOD,
namespace\JAVASCRIPT_DATA_TXTEDITOR_CLASS_MOD,namespace\JAVASCRIPT_FRAGMENT_CLASS_MOD,
namespace\HTML_FRAMESET_PAGE_CLASS_MOD,namespace\HTML_FRAMESET_TAG_CLASS_MOD,
namespace\HTML_FRAME_TAG_CLASS_MOD,namespace\ITEM_STACK_CLASS_MOD,namespace\ITEM_CLASS_MOD,
namespace\DUMPER_CLASS_MOD,namespace\MEMORY_DUMPER_CLASS_MOD,namespace\ECHO_DUMPER_CLASS_MOD,
namespace\FILE_DUMPER_CLASS_MOD,namespace\ARRAY_ITEM_CLASS_MOD,namespace\STRING_ITEM_CLASS_MOD,
namespace\ARG_ITEM_CLASS_MOD,namespace\ASSOCIATIVE_ITEM_CLASS_MOD,namespace\CONSTRUCTOR_CALL_ITEM_CLASS_MOD,
namespace\CONST_ITEM_CLASS_MOD,namespace\DEF_ITEM_CLASS_MOD,namespace\METHOD_CALL_ITEM_CLASS_MOD,
namespace\SECTION_ITEM_CLASS_MOD,namespace\SECTIONS_ITEM_CLASS_MOD,
namespace\VAR_ITEM_CLASS_MOD,namespace\FUNCTION_CALL_ITEM_CLASS_MOD,
namespace\BLOCK_DEF_ITEM_CLASS_MOD,namespace\IF_ELSE_ITEM_CLASS_MOD,
namespace\COND_ITEM_CLASS_MOD,namespace\CONCAT_ITEM_CLASS_MOD,namespace\CLASS_DEF_ITEM_CLASS_MOD,
namespace\CLASS_PROP_ITEM_CLASS_MOD,
namespace\CLASS_VAR_ITEM_CLASS_MOD,namespace\ARGS_LIST_ITEM_CLASS_MOD,namespace\FUNCTION_DEF_ITEM_CLASS_MOD,
namespace\REF_ITEM_CLASS_MOD,namespace\EXPR_ITEM_CLASS_MOD,
namespace\CODE_ITEM_CLASS_MOD,
namespace\COMMENT_ITEM_CLASS_MOD,
namespace\NAMESPACE_ITEM_CLASS_MOD,
namespace\ITEMS_FACTORY_CLASS_MOD,namespace\XML_ITEMS_SERIALIZER_CLASS_MOD,
namespace\HTML_WRITER_CLASS_MOD,namespace\HTML_INTERFACE_DECORATOR_CLASS_MOD,
namespace\HTML_FIELDSET_DECORATOR_CLASS_MOD,
namespace\HTML_UL_TAG_CLASS_MOD,namespace\HTML_OL_TAG_CLASS_MOD,namespace\HTML_LI_TAG_CLASS_MOD,
namespace\HTML_IMG_TAG_CLASS_MOD,
namespace\QUERIES_CONTAINER_CLASS_MOD,
namespace\STACK_CLASS_MOD,namespace\XML_NODE_CLASS_MOD,namespace\JSON_NODE_CLASS_MOD,
namespace\PROFILER_CLASS_MOD,namespace\HTTP_CLIENT_CLASS_MOD,namespace\FCKEDITOR_CLASS_MOD,
/*JPGRAPH_CLASS_MOD,*/namespace\JPGRAPH_BAR_CLASS_MOD,namespace\OBJ_CACHE_CLASS_MOD,
namespace\HTML_INPUT_TAG_CLASS_MOD,namespace\HTML_TEXTAREA_TAG_CLASS_MOD,namespace\HTML_SELECT_TAG_CLASS_MOD,
namespace\HTML_OPTION_TAG_CLASS_MOD,namespace\HTML_DATA_FILE_TEMPLATE_CLASS_MOD,
namespace\DB_ITEM_CONST_MOD,namespace\SERIALIZABLE_NODE_CLASS_MOD,namespace\HTML_FORM_TAG_CLASS_MOD,
namespace\HTML_LABEL_TAG_CLASS_MOD,namespace\HTML_B_TAG_CLASS_MOD,namespace\HTML_HR_TAG_CLASS_MOD,
namespace\STRINGABLE_INT_MOD,namespace\GRAPHITER_INT_MOD,namespace\GENERIC_DB_OP_CLASS_MOD,namespace\ODBC_DB_OP_CLASS_MOD,
namespace\SQLSRV_DB_OP_CLASS_MOD,namespace\DYN_PAGE_LOADER_DEF_MOD,namespace\DYN_PAGE_COMP_HANDLER_CLASS_MOD,
namespace\DYN_PAGE_LOADER_PARSER_GRAMMAR_RULES_CLASS_MOD,namespace\DB_ITEM_PROCESSOR_CLASS_MOD,
namespace\PHPMSGSGEN_CLASS_MOD,namespace\ERROR_HANDLER_DEF_MOD,namespace\XML_DB_MODEL_CLASS_MOD,
namespace\DB_OPS_CONTAINER_CLASS_MOD,namespace\CLASSES_INFO_CLASS_MOD,namespace\INTERFACES_INFO_CLASS_MOD,
namespace\CLONE_CALL_ITEM_CLASS_MOD,namespace\DB_NODES_CONTAINER_CLASS_MOD,
namespace\DB_ITEMS_CONTAINER_CLASS_MOD,
namespace\DB_ITEMS_ITERATOR_CLASS_MOD,namespace\XML_INTERFACE_FILE_ANALYZER_CLASS_MOD,
namespace\UPLOADED_FILE_MANAGER_CLASS_MOD,namespace\INTERFACES_MODEL_CLASS_MOD,
namespace\HTML_A_TAG_CLASS_MOD,namespace\PHP_FRAGMENT_FREE_CLASS_MOD,
namespace\INTERFACE_AS_STRING_CLASS_MOD,
namespace\PHP_ARRAYS_PARSER_GRAMMAR_RULES_CLASS_MOD,
namespace\ITEMS_REQUIRE_ONCES_DEF_MOD,
namespace\AUTOLOAD_INT_MOD,namespace\BOOTSTRAP_INT_MOD,namespace\CONTAINER_INT_MOD,
namespace\CONTENT_INT_MOD,namespace\DECORATOR_INT_MOD,
namespace\DYN_PAGE_INT_MOD,namespace\EXECUTABLE_INT_MOD,namespace\EXECUTABLE_1_INT_MOD,
namespace\EXECUTABLE_2_INT_MOD,namespace\EXECUTABLE_3_INT_MOD,namespace\EXECUTABLE_4_INT_MOD,
namespace\EXECUTABLE_5_INT_MOD,namespace\EXECUTABLE_6_INT_MOD,namespace\EXECUTABLE_7_INT_MOD,
namespace\EXECUTABLE_8_INT_MOD,namespace\EXECUTABLE_9_INT_MOD,
namespace\FACTORY_1_INT_MOD,
namespace\FACTORY_2_INT_MOD,namespace\FACTORY_3_INT_MOD,namespace\FACTORY_4_INT_MOD,
namespace\FACTORY_5_INT_MOD,namespace\FACTORY_6_INT_MOD,namespace\FACTORY_7_INT_MOD,
namespace\FACTORY_8_INT_MOD,namespace\FACTORY_9_INT_MOD,namespace\FACTORY_10_INT_MOD,
namespace\FACTORY_11_INT_MOD,
namespace\GRAPHITER_INT_MOD,
namespace\INIT_1_INT_MOD,namespace\INIT_2_INT_MOD,namespace\INIT_3_INT_MOD,
namespace\OUTPUT_INT_MOD,namespace\STRINGABLE_INT_MOD,namespace\JAVASCRIPT_INT_MOD,
namespace\IITEM_INT_MOD,
namespace\SERIALIZABLE_INT_MOD,
namespace\ITEMS_INT_MOD,
namespace\STANDARD_INT_MOD,
namespace\CSS_INT_MOD,
namespace\JQUERY_INT_MOD,
namespace\DOJO_INT_MOD,
namespace\HTML_TEMPLATE_INT_MOD,
namespace\CALLER_TRA_MOD,namespace\CREATOR_TRA_MOD,
namespace\SERIALIZE_PROPS_TRA_MOD);

$stdDirs = array(JAVASCRIPT_DIR,CSS_DIR,
IMAGES_DIR,XML_DIR,JSON_DIR,CSV_DIR,EDITOR_DIR,JQUERY_DIR,
JQUERY_UI_DIR,DATA_TABLES_DIR,JMENU_DIR,JQUERY_INFINITE_SCROLL_DIR,
DOJO_DIR,SPIN_DIR,ACE_DIR,INTERFACES_DIR,AJAXOPS_DIR,BUTTONS_DIR,
BOOTSTRAP_DIR,FPDF_DIR);

?>